-- #############################################################################################################################################
-- Section 4: Product & Specialty Revenue Contribution
-- Understand which products and services drive the most revenue. This section quantifies the contribution of each specialty
-- to the overall clinic's earnings, critical for strategic planning.
-- #############################################################################################################################################

-- CTE 4.1: unique_procedures
-- Identifies each distinct executed master procedure (LANCTO) and its associated product (PRODUTO). 
-- This is crucial for accurate revenue counting per completed treatment, preventing inflated figures.

WITH unique_procedures AS (
    SELECT DISTINCT
        LANCTO,
        PRODUTO
    FROM
        executed_procedures
),
-- CTE 4.2: general_category_sales calculates the total revenue generated by each dentistry specialty.
-- It aggregates sales values (VRVENDA) for products under each specialty, excluding orthodontic procedures which are handled separately.

general_category_sales AS (
    SELECT
        COUNT(DISTINCT unique_procedures.LANCTO) AS 'total_procedures_count',
        specialities.NOME AS 'category',
        ROUND(SUM(products.VRVENDA)) AS 'revenue_by_specialty'
    FROM
        products
    LEFT JOIN
        specialities ON products.ID_ESPECIALIDADE = specialities.CODIGO
    JOIN
        unique_procedures ON products.CODIGO = unique_procedures.PRODUTO
    GROUP BY
        specialities.NOME
),

-- CTE 4.3: orthodontic_revenue | Calculates the total revenue derived exclusively from orthodontic payments.
-- Orthodontic services often have a distinct payment and recording structure;
-- aggregating this revenue separately ensures its precise financial impact.

orthodontic_revenue AS (
    SELECT
        COUNT(DISTINCT LANCTO) AS 'total_orthodontics_appointments',
        'ORTODONTIA' AS category, 
        ROUND(SUM(VALOR),2) AS 'revenue_by_specialty'
    FROM
        orthodontic_payments
),
-- CTE 4.4: all_category_sales | Combines the revenue data from both general dentistry specialties
-- ('general_category_sales') and orthodontic services ('orthodontic_revenue').
-- This unified view is vital for conducting a financial analysis across the clinic's entire service portfolio.

all_category_sales AS ( 
    SELECT
        category,
        revenue_by_specialty
    FROM
        general_category_sales
    UNION ALL
    SELECT
        category,
        revenue_by_specialty
    FROM
        orthodontic_revenue
)
-- Final Query: Overall Specialty Revenue Contribution Percentage | Presents a complete breakdown of revenue generated by each specialty
-- across the entire clinic, including its percentage contribution to total revenue.

SELECT
    category,
    revenue_by_specialty,
    SUM(revenue_by_specialty) OVER() AS 'total_clinic_revenue', 
    CONCAT(ROUND(revenue_by_specialty / SUM(revenue_by_specialty) OVER()*100,2), "%") AS 'category_contribution_percentage' -- Standardized alias
FROM 
    all_category_sales
ORDER BY
    revenue_by_specialty DESC;